id: 0f983d524f73475caa16d49f6d5ae258
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_193-The_Prophecy_of_Sri_Mahadevi-v1
  language: en
  author: ''
  volume: {}
